config/routes.rb
TweeterApp::Application.routes.draw do
  resources :tweets
  match "read_message" => "tweets#read_message"
<<<<<<< HEAD
  match "update" => "tweet#update_status"
=======
  match "update" => "tweets#update_status"
>>>>>>> 1aab3d3ee540084d763906ca06ae852b2c85ae29

   root :to => 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
<<<<<<< HEAD
	Twitter.configure do |config|
  	config.consumer_key = '49qJyhmQpEtgtlYiAToA'
  	config.consumer_secret = 'IidF8gpiJP0W7Vennb68oy3RvVBeNWHSgdzNPsHWk'
  	config.oauth_token = '51323073-SftK3FzFCoU8hpCGvBZSZ1tFfBXuYT8sGdxnfJD28'
  	config.oauth_token_secret = 'u7dRa46KmV74V3i7Y5p4hz0CjrypVaGlKpVCr5xq31g'
	end

	def read_message
    	return "No hay usuario" if self.user.blank?
    	Twitter.user_timeline(self.user).first.text
	end

	def update_status
		return "Sin update" if self.message.blank?
		Twitter.update(self.message)
	end
end
=======
Twitter.configure do |config|
  config.consumer_key = '49qJyhmQpEtgtlYiAToA'
  config.consumer_secret = 'IidF8gpiJP0W7Vennb68oy3RvVBeNWHSgdzNPsHWk'
  config.oauth_token = '51323073-SftK3FzFCoU8hpCGvBZSZ1tFfBXuYT8sGdxnfJD28'
  config.oauth_token_secret = 'u7dRa46KmV74V3i7Y5p4hz0CjrypVaGlKpVCr5xq31g'
end
  def read_message
    return "No hay usuario" if self.user.blank?
    Twitter.user_timeline(self.user).first.text
  end

  def update_status
  	return "sin update" if self.message.blank?
  	Twitter.update(self.message)
  end
end
>>>>>>> 1aab3d3ee540084d763906ca06ae852b2c85ae29

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
   def read_message
    @tweet = Tweet.new(params[:tweets])

    respond_to do |format|
<<<<<<< HEAD
=======
    format.html # index.html.erb
    format.json { render json: @tweets }
   end
  end
  
  def update_status
     @tweet = Tweet.new(params[:tweet])
     respond_to do |format|
>>>>>>> 1aab3d3ee540084d763906ca06ae852b2c85ae29
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  def update_status
    @tweet = Tweet.new(params[:tweet])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end    
  
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TweeterApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/formReadmessage.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit "Último tweet" %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<%= form_for(@tweet, :url => "user") do |f| %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit "Buscar" %>
  </div>
  <% end %>

  <%= form_for(@tweet, :url => "update") do |f| %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>

 
<% end %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/read_message.html.erb
<h2>último tweet</h2>

<%= @tweet.update_status %>
<%= @tweet.read_message %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @tweet.user %>
</p>

<p>
  <b>Url:</b>
  <%= @tweet.url %>
</p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/update_status.html.erb
<<<<<<< HEAD
<h1>Estado Cambiado</h1>
=======
<h1>Estado cambiado</h1>
>>>>>>> 1aab3d3ee540084d763906ca06ae852b2c85ae29
<% @tweet.update_status %>
<%= @tweet.status %>